name: deploy-pr #for-rerun

on:
  pull_request:
    paths:
      - 'app/**'
      - .github/workflow/deploy-pr.yml

env:
  REGISTRY: ghcr.io

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ github.repository }} #ghcr.io/Yu-Aka/fastapi-sample

      - name: Log in to Github container registry
        uses: docker/login-action@v3
        with:
            registry: ${{ env.REGISTRY }}
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}
    
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
            context: app
            push: true
            tags: ${{ steps.meta.outputs.tags }} #ghcr.io/Yu-Aka/fastapi-sample:pr-xx
            labels: ${{ steps.meta.outputs.tags }} 
